version: '3.8'

services:
  app:
    image: study-front-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:5173
    environment:
      - VITE_REACT_BACKEND_URL=${VITE_REACT_BACKEND_URL}