version: '3.8'

services:
  app:
    image: study-front-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_REACT_BACKEND_URL=${VITE_REACT_BACKEND_URL}
    container_name: study-front-prod
  server:
    image: study-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_URI_TEST=${MONGODB_URI_TEST}
  nginx:
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server