version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 4000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  server:
    image: study-schedule-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
      - MONGODB_URI_TEST=mongodb://the_username:the_password@mongo:27017/test
    command: sh -c 'npm run dev'
